# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaniiCli < Formula
  desc "Scanii CLI — interact with the Scanii API and run a local mock server for integration testing"
  homepage "https://www.scanii.com"
  version "1.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.7.1/scanii-cli-1.7.1-darwin-amd64.tar.gz"
      sha256 "776c1c166084bd86ec70f8583922ca6dca295e83b241d068fb74b52f778dae94"

      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.7.1/scanii-cli-1.7.1-darwin-arm64.tar.gz"
      sha256 "1388e6054ec702cf26afc66506de93022ac4511fdf12244fbdbad9fdfebc0f7a"

      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.7.1/scanii-cli-1.7.1-linux-amd64.tar.gz"
      sha256 "26cb4a51f0a386631f4d5196140254b0e817a9963f6245d7958a50233b51cb4f"
      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.7.1/scanii-cli-1.7.1-linux-arm64.tar.gz"
      sha256 "22b7fb35c55d0ee98a14b496a30a4fa3f0440400452b8a7b840693863790293e"
      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  test do
    system "#{bin}/sc", "version"
  end
end
