# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaniiCli < Formula
  desc "Scanii CLI — interact with the Scanii API and run a local mock server for integration testing"
  homepage "https://www.scanii.com"
  version "1.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.8.0/scanii-cli-1.8.0-darwin-amd64.tar.gz"
      sha256 "8b757405ef27a830948c4602d0194a394912ccb181bb8e6a9c56cc31071bd4e9"

      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.8.0/scanii-cli-1.8.0-darwin-arm64.tar.gz"
      sha256 "16cb4b3424766f16858ecabef671afd27ece880486efcbd9e7ba62f33717949c"

      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.8.0/scanii-cli-1.8.0-linux-amd64.tar.gz"
      sha256 "975ff15f4b666e142f50c65a32504a197e0f3ee91dbdecf8f57fa6fd4cf67ef4"
      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.8.0/scanii-cli-1.8.0-linux-arm64.tar.gz"
      sha256 "cb194ddf2732f17f5dc63444cb498c2d1b8cd6b605f231a64e8abcf99c6fbd6c"
      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  test do
    system "#{bin}/sc", "version"
  end
end
