# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScaniiCli < Formula
  desc "Scanii CLI — interact with the Scanii API and run a local mock server for integration testing"
  homepage "https://www.scanii.com"
  version "1.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.9.0/scanii-cli-1.9.0-darwin-amd64.tar.gz"
      sha256 "757ac171a2a85d39d18dbcf3b8276ae554c82a22b251cc7eebe62d2f0d4d54eb"

      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.9.0/scanii-cli-1.9.0-darwin-arm64.tar.gz"
      sha256 "1e8c02a4b1bb7a935b73dce1052b3b4ae0696229069849ad52c5f6715aebe76c"

      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.9.0/scanii-cli-1.9.0-linux-amd64.tar.gz"
      sha256 "28609a4e0bde74c9e7c80827b6deb59e29105eaaee29b8e1915c04902326a87f"
      define_method(:install) do
        bin.install "sc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scanii/scanii-cli/releases/download/v1.9.0/scanii-cli-1.9.0-linux-arm64.tar.gz"
      sha256 "349d110e8bd44ada0709ea5d431fd24883f9fbaac3dc991dc82a04e193bc278f"
      define_method(:install) do
        bin.install "sc"
      end
    end
  end

  test do
    system "#{bin}/sc", "version"
  end
end
